### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (100,100,0) (100,100,3) 

### ISSUE THREAD

**Issue by sgrtyi** [cyberdoggos/generator#2]
I changed the resolution through config-norm yml, and added the new trait named as same as old names, this only two changes that I made, it gives me only 1/1000 img then this error appears, can you please help me, thanks.

[Running] python -u "c:\Users\****\Documents\***\generator-main\generate.py"
Lossy conversion from float64 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float64 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.
Traceback (most recent call last):
  File "c:\Users\****\Documents\ ****\generator-main\generate.py", line 192, in <module>
    main()
  File "c:\Users\****\Documents\ ****\generator-main\generate.py", line 181, in main
    gen.generate_normal(i, mistakes)
  File "c:\Users\ ****\Documents\ ****\generator-main\generate.py", line 30, in generate_normal
    image, ids[idx], name, value, trait = self.add_layer(image, layer_id, layer, traits)
  File "c:\Users\ ****\Documents\ ****\generator-main\generate.py", line 102, in add_layer
    image = alpha * layer + (1 - alpha) * image
ValueError: operands could not be broadcast together with shapes (100,100,0) (100,100,3)

**Comment by grallc** [comment]
> I changed the resolution through config-norm yml, and added the new trait named as same as old names, this only two changes that I made, it gives me only 1/1000 img then this error appears, can you please help me, thanks.
> 
> [Running] python -u "c:\Users*_**\Documents***\generator-main\generate.py" Lossy conversion from float64 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning. Lossy conversion from float64 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning. Traceback (most recent call last): File "c:\Users*_**\Documents\ *_**\generator-main\generate.py", line 192, in main() File "c:\Users***_\Documents\ ****\generator-main\generate.py", line 181, in main gen.generate_normal(i, mistakes) File "c:\Users\ ****\Documents\ ****\generator-main\generate.py", line 30, in generate_normal image, ids[idx], name, value, trait = self.add_layer(image, layer_id, layer, traits) File "c:\Users\ ****\Documents\ ****\generator-main\generate.py", line 102, in add_layer image = alpha * layer + (1 - alpha) * image ValueError: operands could not be broadcast together with shapes (100,100,0) (100,100,3)

Change the image height/width in the config
